### PR TITLE
remove duplicate add missing and update username

### PR DESCRIPTION
**Pull request by un1versal**
I think all this merging broke something.

### CODE REVIEW

**Comment by un1versal** [comment]
@notspiff ready for you when you are

**Comment by notspiff** [comment]
Thanks, will look at it tomorrow. now; halo5 time ;)
28. okt. 2015 17:11 skrev "un1versal" <notifications@github.com>:

**Comment by un1versal** [comment]
enjoy, fixed an extra curly bracket that strayed in also

**Comment by notspiff** [comment]
thanks. it's not my fault that the kids can't play together ;)

**Comment by un1versal** [comment]
morning, yes, now Ill see if these merges and re-merges breaks my working shadertoy addon, fingers crossed

**Pull request merged**
