### PR TITLE
add led spectrum analyser (modified)

### PR DESCRIPTION
**Pull request by uNiversaI**
See http://forum.kodi.tv/showthread.php?tid=204991&pid=2011733#pid2011733

It works a treat in Kodi (My wife and other women in family all agreed)

screenshot009
screenshot010
screenshot011
screenshot012

### CODE REVIEW

**Comment by notspiff** [comment]
Nice! Please send to topfs2 he is upstream.

**Comment by uNiversaI** [comment]
lol sigh

**Comment by notspiff** [comment]
Understand the annoyment but i would just have to send another sync pull. So I rather pass it to you :p

**Comment by uNiversaI** [comment]
https://github.com/topfs2/visualization.shadertoy/pull/3

Done, I was gonna do the icon as well something similar to what ronie did so he saved me the trouble

in any case (while Im here) I'll let you know here there's something funky with addon installation, I had to copy some files manually to get it to work after installation completed 

see http://forum.kodi.tv/showthread.php?tid=204991&pid=2011704#pid2011704

**Comment by notspiff** [comment]
Yes saw that. kodi itself hasnt gotten the nevessary update to look in multiarch paths. I will propose a patch in a couple of days when i have a suitable tool at hand (ie a nonphone computer).

**Comment by uNiversaI** [comment]
Great, when wsnipex told me it works for him, I was worried that something PEBCAK in my end, glad to know its not :)

Thx for doing the legwork in any case :) now can enjoy the 2d spectrum analyser :)

**Pull request closed without merging**
