### PR TITLE
remove non working and visualizations which crash Kodi

### PR DESCRIPTION
**Pull request by un1versal**
same as https://github.com/topfs2/visualization.shadertoy/pull/8

### CODE REVIEW

**Comment by un1versal** [comment]
sec this to rebase this on yours

**Comment by notspiff** [comment]
please try it as well. i'm looking at beating circles as we speak, the shaders were changes in the gles/dx11 branches.

**Comment by notspiff** [comment]
none of these crash on my box :/ 

beating circles runs fine at 60 fps
polar beats runs fine at 60 fps
revision 2015 is too much for my gpu but does not crash (3 fps).

**Comment by un1versal** [comment]
Ive no idea but thos rebase killed this pull anyway pile of nuts, forget this.

**Comment by notspiff** [comment]
the point is that this will be very GPU dependent, some of those shaders require much beef. i am however very interested if you see actual *crashes* and not just low fps.

**Comment by un1versal** [comment]
crashes yes, well get to that later however.

**Pull request closed without merging**
