### PR TITLE
shader list is read from json file using zserge/jsmn

### PR DESCRIPTION
**Pull request by circulosmeos**
I've been [playing around with this project](https://github.com/circulosmeos/visualization.shadertoy), and you may be interested in this feature: an external json to store the list of shaders. I've used [zserge/jsmn](https://github.com/zserge/jsmn) minimal C json-reader (MIT license).

This way any user can change the list of shaders. I've done this myself with more than 50 [new shaders tested for GLESv2 (Mali450) from shadertoy.com](https://github.com/circulosmeos/visualization.shadertoy/wiki)

Sorry & WARNING: I've compiled and thoroughly test this with Krypton branch, but not with this Leia branch.
Maybe I should've pulled to Krypton... or two both. Or neither. I don't know.

### CODE REVIEW

**Review by Rechi — CHANGES_REQUESTED** [review]
First there is no need to create a new PR every time you want to change something. Just update the PR branch (jsmn-json) and the PR will get updated automatically.

Including the source code of library into this repo is the wrong approach, it has to be added as a dependency.
There is no need to use a C library, you can use a C++ library (e.g.. libjsoncpp, rapidjson or nlohmann_json).
Also please writing code in C++11 instead of plain C.

**Comment by circulosmeos** [comment]
> First there is no need to create a new PR every time you want to change something. Just update the PR branch (jsmn-json) and the PR will get updated automatically.

Yes, I tried to make a single commit so that it can be later clearly studied or used. Just a mania :-o

> Including the source code of library into this repo is the wrong approach, it has to be added as a dependency.
> There is no need to use a C library, you can use a C++ library (e.g.. libjsoncpp, rapidjson or nlohmann_json).
> Also please writing code in C++11 instead of plain C.

Yeah, that's all true. Unfortunately I made this for testing purposes (the json was a MUST for playing with glsl's) and now I do not have enough spare time to clean all those things :-(  But maybe someone else will get inspired by the concept...
This has been an attempt to provide [ODROID](https://www.hardkernel.com/shop/odroid-c2/) users with a usable (GPU reset animations every 8 s) and improved version.

**Comment by AlwinEsch** [comment]
With this https://github.com/xbmc/visualization.shadertoy/pull/43 the code is cleaned up and only one list with shader files.

Also becomes with https://github.com/xbmc/visualization.shadertoy/pull/44 the `src/main.cpp` also used on Windows.

**Comment by AlwinEsch** [comment]
Have taken your code and changed/cleaned up to work with latest changes.

You can take from here https://github.com/AlwinEsch/visualization.shadertoy/commit/8eab6e4637fa48506e57fd593237944528b65ec0 and change if needed.

**Comment by AlwinEsch** [comment]
As no update was come, created own request https://github.com/xbmc/visualization.shadertoy/pull/75 about.

This becomes closed.

**Pull request closed without merging**
