### PR TITLE
fix debian packaging

### PR DESCRIPTION
**Pull request by wsnipex**
probably unrelated, but I get crashes with kodi master:
http://paste.ubuntu.com/23210571/

### CODE REVIEW

**Comment by notspiff** [comment]
will look into crash. thanks.

**Comment by akva2** [comment]
cannot reproduce the crash :/ will try with the deb when i have a box i can play a little bit more with.

**Comment by wsnipex** [comment]
thanks. I'm running a dual screen setup here although I also tried with the 2nd screen disabled.
Since it crashes in glXQueryVersion/XQueryExtension it might have something to do with that?
Will try at home in the evening as well.

**Comment by akva2** [comment]
i have 4 screens and 2 gpus and it's still happy ;)

but yeah, it could be related. this is a nvidia setup.

**Comment by wsnipex** [comment]
nope, happens on my laptop as well. Again intel gfx though.

**Comment by axbmcuser** [comment]
Did not try shadertoy for some time, but with latest KODI nightlies i also can't get it to work on LibreELEC/linux (intel gpu). Instant crash as soon as the addon loads. On windows with same days nightly (intel gpu, other machine): no problems. I'll see if i can get a debug log tonight, but as far as i remember, there was nothing suspicious in the log which could be much of a help. Thanks!

**Comment by notspiff** [comment]
please try HEAD. i have identified and fixed two issues.

**Comment by wsnipex** [comment]
still fails on intel :(

**Comment by notspiff** [comment]
can you try the 'glee' branch please?

**Comment by notspiff** [comment]
i dug out my old laptop and can reproduce a crash. that ^^ fixes it for me. if you are seeing the same crash as i am (this is some bastardized ubuntu 15.04 on intel skylake hardware), projectM should crash and burn just as hard.

**Comment by notspiff** [comment]
i dropped glew completely. it fixes my crash and is an improvement all over.

**Comment by axbmcuser** [comment]
My crashes on intel are now gone. Thank you very much.

**Pull request merged**
